language: php

# lock distro so new future defaults will not break the build
dist: trusty

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: hhvm-3.18
# ppc64le related code
    - php: 5.3
      arch: ppc64le
      dist: precise
    - php: 5.4
      arch: ppc64le
    - php: 5.5
      arch: ppc64le
    - php: 5.6
      arch: ppc64le
    - php: 7.0
      arch: ppc64le
    - php: 7.1
      arch: ppc64le
    - php: 7.2
      arch: ppc64le
    - php: 7.3
      arch: ppc64le
    - php: 7.4
      arch: ppc64le
    - php: hhvm-3.18
      arch: ppc64le
  allow_failures:
    - php: hhvm-3.18
    - php: hhvm-3.18
      arch: ppc64le

install:
  - composer install

script:
  - if [[ "$TRAVIS_PHP_VERSION" > "7.2" ]]; then vendor/bin/phpunit --coverage-text; fi
  - if [[ "$TRAVIS_PHP_VERSION" < "7.3" ]]; then vendor/bin/phpunit --coverage-text -c phpunit.xml.legacy; fi
